export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAIL = 'CREATE_FEEDBACK_FAIL';

export const GET_FEEDBACK_REQUEST = 'GET_FEEDBACK_REQUEST';
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL';

export const UPDATE_FEEDBACK_REQUEST = 'UPDATE_FEEDBACK_REQUEST';
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAIL = 'UPDATE_FEEDBACK_FAIL';

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL';

export const CLEAR_FEEDBACK_ERRORS = 'CLEAR_FEEDBACK_ERRORS';
export const CLEAR_FEEDBACK_MESSAGE = 'CLEAR_FEEDBACK_MESSAGE';

export const GET_ALL_FEEDBACKS_REQUEST = 'GET_ALL_FEEDBACKS_REQUEST';
export const GET_ALL_FEEDBACKS_SUCCESS = 'GET_ALL_FEEDBACKS_SUCCESS';
export const GET_ALL_FEEDBACKS_FAIL = 'GET_ALL_FEEDBACKS_FAIL';